version: '3.7'

services:
  iseecockpit-dev:
    container_name: isee4xai/cockpit:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src
