name: Docker Image CI

on:
  push:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push  the Docker image
      uses: docker/build-push-action@v2
      env:
        REACT_APP_ISEE_API: https://api-dev.isee4xai.com/api
        REACT_APP_ISEE_ONTOAPI: https://api-onto-dev.isee4xai.com/api
      with:
          push: true
          file: Dockerfile.dev
          tags: isee4xai/cockpit:dev
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy on dev platform 
    steps:
      - uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_DEV }}
          webhook_secret: ${{ secrets.WEBHOOK_TOKEN_DEV }}
          data: '{"DOCKER_PULL_SERVICES":"cockpit"}'
          webhook_type: 'json-extended'
          
          
